version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./myproject:/app
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    image: php82-fpm
    working_dir: /app
    volumes:
      - ./myproject:/app
      - /app/vendor/
    extra_hosts:
      - host_machine:host-gateway
    environment:
      - ENV=local
      - MYSQL_DATABASE=test
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=SyXrYVdrF9XehuurXsK3sHhl
      - MYSQL_HOST=host_machine
      - MONGO_CONN=mongodb://host_machine:27017,host_machine:27018,host_machine:27019
      - MONGO_DB=surex
    #run first time : docker compose exec php-fpm composer install